import type { Metadata } from "next";
import SiteHeader from "../../components/SiteHeader";
import type { Bid } from "../../data";
import { won } from "../../data";
import { findBid } from "../../../lib/live-bids";

export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const bid=await findBid(id);if(!bid)return{title:"공고를 찾을 수 없습니다 | 비드인사이트"};const description=`${bid.agency} ${bid.category} 입찰공고. 투찰마감 ${bid.deadline}.`;return{title:`${bid.title} | 비드인사이트`,description,openGraph:{title:bid.title,description,images:[]},twitter:{title:bid.title,description,images:[]}}}

export default async function BidDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;const bid=await findBid(id);if(!bid)return <div className="page-shell"><SiteHeader/><div className="page-wrap"><div className="panel empty">공고를 찾을 수 없습니다. <a href="/bids">목록으로 돌아가기</a></div></div></div>;
return <div className="page-shell"><SiteHeader active="bids"/><div className="page-wrap"><div className="page-title"><div className="crumb">홈 〉 입찰공고 〉 공고상세</div></div><div className="detail-grid"><article className="panel detail-main"><div className="detail-top"><span className={`cat ${bid.category}`}>{bid.category}</span><div><span className="status-pill">{bid.status}</span><h1>{bid.title}</h1><p>{bid.number} · 공고일 {bid.announced}</p></div><button className="fav" aria-label="관심공고 저장">☆</button></div><div className="warning">⚠ 실제 참가 자격과 공고 조건은 반드시 나라장터 원문 및 첨부파일을 최종 확인해야 합니다.</div><nav className="tabs" aria-label="상세정보 탭"><a className="active" href="#basic">기본정보</a><a href="#qualification">참가자격</a><a href="#schedule">일정</a><a href="#amount">금액정보</a><a href="#files">첨부파일</a></nav><Info bid={bid}/></article><aside><div className="panel side-card"><div className="countdown"><small>투찰 마감까지</small><strong>{bid.status==="마감임박"?"오늘 마감":"진행 중"}</strong><span>{bid.deadline}</span></div><div className="side-price"><div><span>배정예산</span><strong>{won(bid.basePrice)}</strong></div><div><span>추정가격</span><strong>{won(bid.estimatePrice)}</strong></div></div><div className="side-actions"><button className="btn primary">☆ 관심공고 저장</button><button className="btn">알림 설정</button><button className="btn">공고 링크 복사</button><a className="btn" href={bid.originalUrl||"https://www.g2b.go.kr/"} target="_blank" rel="noreferrer" style={{display:"grid",placeItems:"center",textDecoration:"none"}}>나라장터 원문 보기 ↗</a></div><p className="source-note">조달청 OpenAPI 제공정보입니다. 실제 투찰 전 나라장터 원문과 첨부파일을 확인하세요.</p></div></aside></div></div></div>}

function Info({bid}:{bid:Bid}){return <><section className="info-section" id="basic"><h2>기본정보</h2><div className="info-grid"><Item label="발주기관" value={bid.agency}/><Item label="수요기관" value={bid.demand}/><Item label="입찰방식" value={bid.method}/><Item label="계약방법" value={bid.contract}/><Item label="지역제한" value={bid.region}/><Item label="예가방식" value="공고문 참조"/></div></section><section className="info-section" id="qualification"><h2>참가자격</h2><div className="info-grid"><Item label="업종·면허 제한" value={bid.license}/><Item label="참가자격 안내" value={bid.qualification}/></div></section><section className="info-section" id="schedule"><h2>입찰 일정</h2><div className="info-grid"><Item label="공고일" value={bid.announced}/><Item label="투찰 마감" value={bid.deadline}/><Item label="개찰 일시" value={bid.opening}/><Item label="개찰 장소" value="나라장터 국가종합전자조달시스템"/></div></section><section className="info-section" id="amount"><h2>금액정보</h2><div className="info-grid"><Item label="배정예산" value={won(bid.basePrice)}/><Item label="추정가격" value={won(bid.estimatePrice)}/></div></section><section className="info-section" id="files"><h2>첨부파일</h2><div className="demo-notice">첨부 공고문과 제안요청서는 나라장터 원문에서 최종 확인하세요.</div></section></>}
function Item({label,value}:{label:string,value:string}){return <div className="info-item"><small>{label}</small><span>{value}</span></div>}
