import type { Bid } from "../app/data";
import { bids as demoBids } from "../app/data";
import { fetchG2B } from "./g2b";

type Raw=Record<string,string|number|null>;
let cache:{expires:number;items:Bid[]}|null=null;
const operations:[Bid["category"],string][]=[["공사","getBidPblancListInfoCnstwk"],["용역","getBidPblancListInfoServc"],["물품","getBidPblancListInfoThng"]];
function kstStamp(date:Date){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date);const get=(type:string)=>parts.find(p=>p.type===type)?.value??"00";return `${get("year")}${get("month")}${get("day")}${get("hour")}${get("minute")}`}
function str(item:Raw,key:string,fallback=""){const value=item[key];return value===null||value===undefined?fallback:String(value)}
function amount(item:Raw,...keys:string[]){for(const key of keys){const n=Number(item[key]);if(Number.isFinite(n)&&n>0)return n}return 0}
function shortDate(value:string){return value?value.replace("T"," ").slice(0,16):"-"}
function mapBid(item:Raw,category:Bid["category"]):Bid{const deadline=shortDate(str(item,"bidClseDt"));const announced=shortDate(str(item,"bidNtceDt"));const deadlineMs=Date.parse(deadline.replace(" ","T")+"+09:00");const left=deadlineMs-Date.now();const today=kstStamp(new Date()).slice(0,8);const status:Bid["status"]=left>0&&left<=86400000?"마감임박":announced.replaceAll("-","").slice(0,8)===today?"신규":"진행중";const bidNo=str(item,"bidNtceNo");return{id:bidNo,number:`${bidNo}-${str(item,"bidNtceOrd","000")}`,category,title:str(item,"bidNtceNm","제목 없음"),agency:str(item,"ntceInsttNm","발주기관 미상"),demand:str(item,"dminsttNm",str(item,"ntceInsttNm","수요기관 미상")),region:str(item,"jntcontrctDutyRgnNm1")||"전국",basePrice:amount(item,"asignBdgtAmt","presmptPrce"),estimatePrice:amount(item,"presmptPrce","asignBdgtAmt"),announced:announced.slice(0,10),deadline,opening:shortDate(str(item,"opengDt")),status,method:str(item,"bidMethdNm","전자입찰"),contract:str(item,"cntrctCnclsMthdNm","공고문 참조"),license:str(item,"pubPrcrmntClsfcNm","공고문 참조"),qualification:"참가자격과 면허·지역 제한은 나라장터 원문 및 첨부 공고문을 확인하세요.",originalUrl:str(item,"bidNtceDtlUrl",str(item,"bidNtceUrl","https://www.g2b.go.kr/"))}}
export async function loadBids():Promise<{items:Bid[];isLive:boolean;message?:string}>{if(!process.env.DATA_GO_KR_SERVICE_KEY||!process.env.G2B_API_BASE_URL)return{items:demoBids,isLive:false,message:"API 환경변수가 없어 데모 데이터를 표시합니다."};if(cache&&cache.expires>Date.now())return{items:cache.items,isLive:true};try{const end=new Date();const start=new Date(end.getTime()-3*86400000);const params={pageNo:"1",numOfRows:"20",inqryDiv:"1",inqryBgnDt:kstStamp(start),inqryEndDt:kstStamp(end)};const groups=await Promise.all(operations.map(async([category,path])=>(await fetchG2B(path,params)).map(item=>mapBid(item,category))));const now=kstStamp(new Date());const items=groups.flat().filter(b=>b.id&&b.deadline!=="-"&&b.deadline.replace(/[- :]/g,"")>=now).sort((a,b)=>a.deadline.localeCompare(b.deadline));if(!items.length)throw new Error("진행 중인 최근 공고 응답이 비어 있습니다.");cache={items,expires:Date.now()+10*60_000};return{items,isLive:true}}catch(error){return{items:demoBids,isLive:false,message:error instanceof Error?`실시간 연결 오류: ${error.message}`:"실시간 연결 오류"}}}
export async function findBid(id:string){const live=await loadBids();return live.items.find(b=>b.id===id)??demoBids.find(b=>b.id===id)??null}
