type Raw=Record<string,string|number|null>;
export type Award={id:string;number:string;title:string;category:string;agency:string;company:string;awardAmount:number;plannedPrice:number;rate:string;openedAt:string;method:string};
let cache:{expires:number;items:Award[]}|null=null;
const BASE="https://apis.data.go.kr/1230000/ao/PubDataOpnStdService/";
const divisions=[["1","물품"],["3","공사"],["5","용역"]] as const;
const str=(item:Raw,key:string,fallback="")=>item[key]===null||item[key]===undefined?fallback:String(item[key]);
const num=(item:Raw,...keys:string[])=>{for(const key of keys){const value=Number(item[key]);if(Number.isFinite(value)&&value>0)return value}return 0};
function kstDay(date:Date){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(date).replaceAll("-","")}
function normalize(item:Raw,category:string):Award{return{id:str(item,"bidNtceNo"),number:`${str(item,"bidNtceNo")}-${str(item,"bidNtceOrd","000")}`,title:str(item,"bidNtceNm","공고명 없음"),category:str(item,"bsnsDivNm",category),agency:str(item,"ntceInsttNm","공고기관 미상"),company:str(item,"fnlSucsfCorpNm",str(item,"bidprcCorpNm","낙찰업체 확인 중")),awardAmount:num(item,"fnlSucsfAmt","bidprcAmt"),plannedPrice:num(item,"rsrvtnPrce","presmptPrce","bssAmt"),rate:str(item,"fnlSucsfRt",str(item,"bidprcRt","-")),openedAt:`${str(item,"opengDate",str(item,"fnlSucsfDate"))} ${str(item,"opengTm")}`.trim(),method:str(item,"bidwinrDcsnMthdNm",str(item,"cntrctCnclsMthdNm","공고문 참조"))}}
async function fetchDay(key:string,day:string,code:string,category:string){const url=new URL("getDataSetOpnStdScsbidInfo",BASE);url.search=new URLSearchParams({serviceKey:key,pageNo:"1",numOfRows:"30",type:"json",bsnsDivCd:code,opengBgnDt:`${day}0000`,opengEndDt:`${day}2359`}).toString();const response=await fetch(url,{headers:{accept:"application/json"}});if(!response.ok)throw new Error(`낙찰 API ${response.status}`);const data=await response.json() as {response?:{header?:{resultCode?:string;resultMsg?:string};body?:{items?:Raw[]|{item?:Raw[]}}}};if(data.response?.header?.resultCode!=="00")throw new Error(data.response?.header?.resultMsg||"낙찰 API 오류");const items=data.response.body?.items;const list=Array.isArray(items)?items:items?.item??[];return list.map(item=>normalize(item,category))}
export async function loadAwards():Promise<{items:Award[];isLive:boolean;message?:string}>{const rawKey=process.env.DATA_GO_KR_SERVICE_KEY;if(!rawKey)return{items:[],isLive:false,message:"API 환경변수가 없습니다."};if(cache&&cache.expires>Date.now())return{items:cache.items,isLive:true};let key=rawKey;try{key=decodeURIComponent(rawKey)}catch{}try{const tasks:Promise<Award[]>[]=[];for(let offset=0;offset<3;offset++){const date=new Date(Date.now()-offset*86400000);const day=kstDay(date);for(const [code,category] of divisions)tasks.push(fetchDay(key,day,code,category))}const groups=await Promise.all(tasks);const map=new Map<string,Award>();for(const award of groups.flat()){if(!award.id)continue;const current=map.get(award.id);if(!current||award.company!=="낙찰업체 확인 중")map.set(award.id,award)}const items=[...map.values()].sort((a,b)=>b.openedAt.localeCompare(a.openedAt));cache={items,expires:Date.now()+10*60_000};return{items,isLive:true}}catch(error){return{items:[],isLive:false,message:error instanceof Error?error.message:"낙찰정보 연결 오류"}}}
