import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const profiles=sqliteTable("profiles",{id:text("id").primaryKey(),email:text("email").notNull(),displayName:text("display_name"),role:text("role").notNull().default("user"),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const companies=sqliteTable("companies",{id:integer("id").primaryKey({autoIncrement:true}),userId:text("user_id").notNull(),name:text("name").notNull(),businessNumber:text("business_number"),region:text("region"),licenses:text("licenses",{mode:"json"}),preferences:text("preferences",{mode:"json"})},t=>[index("companies_user_idx").on(t.userId)]);
export const bids=sqliteTable("bids",{id:integer("id").primaryKey({autoIncrement:true}),source:text("source").notNull().default("G2B"),bidNumber:text("bid_number").notNull(),bidOrder:text("bid_order").notNull().default("000"),title:text("title").notNull(),category:text("category").notNull(),status:text("status").notNull(),orderingAgency:text("ordering_agency"),demandingAgency:text("demanding_agency"),region:text("region"),estimatedPrice:integer("estimated_price"),basePrice:integer("base_price"),announcementAt:integer("announcement_at",{mode:"timestamp"}),bidStartAt:integer("bid_start_at",{mode:"timestamp"}),bidDeadlineAt:integer("bid_deadline_at",{mode:"timestamp"}),openingAt:integer("opening_at",{mode:"timestamp"}),contractMethod:text("contract_method"),bidMethod:text("bid_method"),originalUrl:text("original_url"),rawData:text("raw_data",{mode:"json"}),createdAt:integer("created_at",{mode:"timestamp"}).notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()},t=>[uniqueIndex("bids_number_order_uidx").on(t.bidNumber,t.bidOrder),index("bids_title_idx").on(t.title),index("bids_category_idx").on(t.category),index("bids_region_idx").on(t.region),index("bids_deadline_idx").on(t.bidDeadlineAt)]);
export const favorites=sqliteTable("favorites",{id:integer("id").primaryKey({autoIncrement:true}),userId:text("user_id").notNull(),bidId:integer("bid_id").notNull(),createdAt:integer("created_at",{mode:"timestamp"}).notNull()},t=>[uniqueIndex("favorites_user_bid_uidx").on(t.userId,t.bidId)]);
export const savedSearches=sqliteTable("saved_searches",{id:integer("id").primaryKey({autoIncrement:true}),userId:text("user_id").notNull(),name:text("name").notNull(),filters:text("filters",{mode:"json"}).notNull(),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const alertRules=sqliteTable("alert_rules",{id:integer("id").primaryKey({autoIncrement:true}),userId:text("user_id").notNull(),name:text("name").notNull(),filters:text("filters",{mode:"json"}).notNull(),channels:text("channels",{mode:"json"}).notNull(),enabled:integer("enabled",{mode:"boolean"}).notNull().default(true),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const alertLogs=sqliteTable("alert_logs",{id:integer("id").primaryKey({autoIncrement:true}),userId:text("user_id").notNull(),ruleId:integer("rule_id"),bidId:integer("bid_id"),eventType:text("event_type").notNull(),status:text("status").notNull(),dedupeKey:text("dedupe_key").notNull(),sentAt:integer("sent_at",{mode:"timestamp"})},t=>[uniqueIndex("alert_logs_dedupe_uidx").on(t.dedupeKey)]);
export const userMemos=sqliteTable("user_memos",{id:integer("id").primaryKey({autoIncrement:true}),userId:text("user_id").notNull(),bidId:integer("bid_id").notNull(),content:text("content").notNull(),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()});
export const syncLogs=sqliteTable("api_sync_logs",{id:integer("id").primaryKey({autoIncrement:true}),service:text("service").notNull(),status:text("status").notNull(),itemCount:integer("item_count").notNull().default(0),message:text("message"),startedAt:integer("started_at",{mode:"timestamp"}).notNull(),finishedAt:integer("finished_at",{mode:"timestamp"})});
export const adminActivityLogs=sqliteTable("admin_activity_logs",{id:integer("id").primaryKey({autoIncrement:true}),adminUserId:text("admin_user_id").notNull(),action:text("action").notNull(),target:text("target"),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
